routes/web.php
<?php
// Common
include('Common.php');

// Front End routes
include('Frontend.php');

// Backoffice routes
include('Backoffice.php');

// Contact UsA
Route::post('/contact_us', 'ContactUsController@send')->name('contact_us');

// Webhooks
Route::post('webhook/stripe', 'WebhookController@handleStripeCallback'); 		// Stripe

// AJAX routes for get images
// Route::get('order/ajax/taxrate', 'OrderController@ajaxTaxRate')->name('ajax.taxrate');

Route::get("/signup","Storefront\HomeController@getSignUp");

app/User.php
<?php

namespace App;

use Hash;
use App\Common\Imageable;
use App\Common\Addressable;
use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
// use Spatie\Activitylog\Traits\HasActivity;
use Illuminate\Database\Eloquent\SoftDeletes;
// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

// class User extends Authenticatable implements MustVerifyEmail
class User extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable, Addressable, Imageable;

   /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
                    'password',
                    'remember_token',
                    'verification_token',
                ];


    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'dob'           => 'date',
        'deleted_at'    => 'datetime',
        'last_visited_at' => 'datetime',
        'read_announcements_at' => 'datetime',
        'active'        => 'boolean',
    ];

    /**
     * The attributes that will be logged on activity logger.
     *
     * @var boolean
     */
    protected static $logFillable = true;

    /**
     * The only attributes that has been changed.
     *
     * @var boolean
     */
    protected static $logOnlyDirty = true;

    /**
     * The name that will be used when log this model. (optional)
     *
     * @var boolean
     */
    protected static $logName = 'user';

    /**
     * Route notifications for the mail channel.
     *
     * @return string
     */
    public function routeNotificationForMail()
    {
        return $this->email;
    }

    /**
     * Route notifications for the Nexmo channel.
     *
     * @return string
     */
    public function routeNotificationForNexmo()
    {
        return $this->primaryAddress->phone;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
                    'shop_id',
                    'role_id',
                    'name',
                    'nice_name',
                    'email',
                    'password',
                    'dob',
                    'description',
                    'sex',
                    'active',
                    'last_visited_at',
                    'last_visited_from',
                    'read_announcements_at',
                    'remember_token',
                    'verification_token',
                ];

    /**
     * Get the dashboard of the user.
     */
    public function dashboard()
    {
        return $this->hasOne(Dashboard::class, 'user_id');
    }

    /**
     * Get all of the country for the country.
     */
    public function country()
    {
        return $this->hasManyThrough(Country::class, Address::class, 'addressable_id', 'country_name');
    }

    /**
     * Get the Roles associated with the user.
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    /**
     * Get the shop associated with the user.
    */
    public function shop()
    {
        return $this->belongsTo(Shop::class)->withDefault();
    }

    /**
     * Get the shops the user own.
    */
    public function owns()
    {
        return $this->hasOne(Shop::class, 'owner_id')->withTrashed()->withDefault();
    }

    /**
     * Get the Warehouses associated with the user.
     */
    public function warehouses()
    {
        return $this->belongsToMany(Warehouse::class)->withTimestamps();
    }

    /**
     * Get the user incharges of the warehouses.
     */
    public function incharges()
    {
        return $this->hasMany(Warehouse::class, 'incharge');
    }

    /**
     * Get the user messages of the warehouses.
     */
    public function messages()
    {
        return $this->hasMany(Message::class, 'user_id');
    }

    public function assignedTickets()
    {
        return $this->hasMany(Ticket::class, 'assigned_to');
    }

    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function openTickets()
    {
        return $this->tickets()->where('status', '<', Ticket::STATUS_SOLVED);
    }

    public function solvedTickets()
    {
        return $this->tickets()->where('status', '=', Ticket::STATUS_SOLVED);
    }

    public function closedTickets()
    {
        return $this->tickets()->where('status', '=', Ticket::STATUS_CLOSED);
    }

    /**
     * User has many blog post
     */
    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }

    /**
     * Get dob for the user.
     *
     * @return array
     */
    public function getDobAttribute($dob)
    {
        if($dob)
            return date('Y-m-d', strtotime($dob));
    }

    /**
     * Get role list for the user.
     *
     * @return array
     */
    public function getRoleListAttribute()
    {
        if (count($this->roles)) return $this->roles->pluck('id')->toArray();
    }

    /**
     * Set password for the user.
     *
     * @return array
     */
    public function setPasswordAttribute($password)
    {
        if(Hash::needsRehash($password))
            $this->attributes['password'] = bcrypt($password);
        else
            $this->attributes['password'] = $password;
    }

    /**
     * Get name the user.
     *
     * @return mix
     */
    public function getName()
    {
        return $this->nice_name ?: $this->name;
    }

    /**
     * Get merchant id for the user.
     *
     * @return mix
     */
    public function merchantId()
    {
        return $this->shop_id;
    }

    /**
     * Get current plan
     *
     * @return mix
     */
    public function getCurrentPlan()
    {
        if( ! $this->merchantId() )  return Null;

        $subscription = optional($this->shop->subscriptions)->first();

        if($subscription && $subscription->valid())
            return $subscription;

        return Null;
    }

    /**
     * Check if the user is the super admin
     *
     * @return bool
     */
    public function isSuperAdmin()
    {
        return $this->role_id == Role::SUPER_ADMIN;
    }

    /**
     * Check if the user is the super admin or admin
     *
     * @return bool
     */
    public function isAdmin()
    {
        return $this->isSuperAdmin() || $this->role_id == Role::ADMIN;
    }

    /**
     * Check if the user is from main platform or not
     *
     * @return bool
     */
    public function isFromPlatform()
    {
        return ! $this->isMerchant() && ! $this->merchantId();
    }

    /**
     * Check if the user is from a Merchant or not
     *
     * @return bool
     */
    public function isFromMerchant()
    {
        return $this->isMerchant() || $this->merchantId();
    }

    /**
     * Check if the user is a Merchant
     *
     * @return bool
     */
    public function isMerchant()
    {
        return $this->role_id == Role::MERCHANT;
    }

    /**
     * Check if the user is Verified
     *
     * @return bool
     */
    public function isVerified()
    {
        return $this->verification_token == Null;
    }

    /**
     * Check if the user is has billing token
     *
     * @return bool
     */
    public function hasBillingToken()
    {
        return $this->merchantId() && $this->shop->hasStripeId();
    }

    /**
     * Check if the user has outrange plan
     *
     * @return bool
     */
    public function hasExpiredPlan()
    {
        if(!$this->merchantId())        return false;

        $subscription = $this->shop->subscriptions->first();

        if ($subscription && ! is_null($subscription->ends_at))
            return \Carbon\Carbon::now()->gt($subscription->ends_at);

        return false;
    }

    /**
     * Check if the user has outrange generic plan
     *
     * @return bool
     */
    public function hasExpiredOnGenericTrial()
    {
        return $this->shop->trial_ends_at && $this->shop->trial_ends_at->isPast();
    }

    /**
     * Check if the user is subscribed
     *
     * @return bool
     */
    public function isSubscribed()
    {
        if($this->isFromPlatform() || !$this->merchantId())
            return False;

        $subscription = optional($this->shop->subscriptions)->first();

        return $subscription && $subscription->valid() || $this->isOnGenericTrial();
    }

    /**
     * Check if the user is isOnGenericTrial without card
     *
     * @return bool
     */
    public function isOnGenericTrial()
    {
        return $this->shop->onGenericTrial();
    }

    /**
     * Check if the user is OnTrial
     *
     * @return bool
     */
    public function isOnTrial()
    {
        $subscription = $this->shop->subscriptions->first();

        return $subscription && $subscription->onTrial();
    }

    /**
     * Check if the user is onGracePeriod
     *
     * @return bool
     */
    public function isOnGracePeriod()
    {
        $subscription = $this->shop->subscriptions->first();

        return $subscription && $subscription->onGracePeriod();
    }

    /**
     * Check if access level the user
     *
     * @return bool
     */
    public function accessLevel()
    {
        return $this->role->level ? $this->role->level + 1 : Null;
    }

    /**
     * Activities for the loggable model
     *
     * @return [type] [description]
     */
    public function activities()
    {
        return $this->activity()->orderBy('created_at', 'desc')->get();
    }

    /**
     * Check if the user is the super admin
     *
     * @return bool
     */
    public function scopeNotSuperAdmin($query)
    {
        return $query->where('role_id', '!=', Role::SUPER_ADMIN);
    }

    /**

app/Http/Controllers/Installer/ActivateController.php
<?php

namespace App\Http\Controllers\Installer;

use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Routing\Controller;
// use App\Http\Controllers\Installer\Helpers\DatabaseManager;

class ActivateController extends Controller
{
    /**
     * @var DatabaseManager
     */
    // private $databaseManager;

    /**
     * @param DatabaseManager $databaseManager
     */
    // public function __construct(DatabaseManager $databaseManager)
    // {
    //     $this->databaseManager = $databaseManager;
    // }

    /**
     * Migrate and seed the database.
     *
     * @return \Illuminate\View\View
     */
    public function activate()
    {
//        if ( ! $this->checkDatabaseConnection() ) {
//            return redirect()->back()->withErrors([
//                'database_connection' => trans('installer_messages.environment.wizard.form.db_connection_failed'),
//            ]);
//        }

        return view('installer.activate');
    }

    public function verify(Request $request)
    {
        $mysqli_connection = getMysqliConnection();

        if ( ! $mysqli_connection )
            return redirect()->route('Installer.activate')->with(['failed' => trans('responses.database_connection_failed')])->withInput($request->all());

//        $purchase_verification = aplVerifyEnvatoPurchase($request->purchase_code);
//        if (!empty($purchase_verification)) //protected script can't connect to your licensing server
//            return redirect()->route('Installer.activate')->with(['failed' => 'Connection to remote server can\'t be established'])->withInput($request->all());

//        $license_notifications_array = incevioVerify($request->root_url, $request->email_address, $request->purchase_code, $mysqli_connection);
        $license_notifications_array = ["notification_case" => "notification_license_ok"];

//        if ($license_notifications_array['notification_case'] == "notification_license_ok")
            return view('installer.install', compact('license_notifications_array'));

//        if ($license_notifications_array['notification_case'] == "notification_already_installed") {
//            $license_notifications_array = incevioAutoloadHelpers($mysqli_connection, 1);

//            if ($license_notifications_array['notification_case'] == "notification_license_ok")
//                return view('installer.install', compact('license_notifications_array'));
//        }

//        return redirect()->route('Installer.activate')->with(['failed' => $license_notifications_array['notification_text']])->withInput($request->all());

//        $license_notifications_array = [];
//
//        return view('installer.install', compact('license_notifications_array'));

    }

    /**
     * Validate database connection with user credentials (Form Wizard).
     *
     * @return boolean
     */
    private function checkDatabaseConnection()
    {
        try {
            DB::connection()->getPdo();
            return true;
        } catch (Exception $e) {
            return false;
        }
    }

    /**
     * Return a formatted error messages.
     *
     * @param $message
     * @param string $status
     * @return array
     */
    private function response($message, $status = 'danger')
    {
        return [
            'status' => $status,
            'message' => $message,
        ];
    }
}

app/Http/Controllers/Installer/DatabaseController.php
<?php

namespace App\Http\Controllers\Installer;

use Exception;
use Illuminate\Support\Facades\DB;
use Illuminate\Routing\Controller;
use App\Http\Controllers\Installer\Helpers\DatabaseManager;

class DatabaseController extends Controller
{
    /**
     * @var DatabaseManager
     */
    private $databaseManager;

    /**
     * @param DatabaseManager $databaseManager
     */
    public function __construct(DatabaseManager $databaseManager)
    {
        $this->databaseManager = $databaseManager;
    }

    /**
     * Migrate and seed the database.
     *
     * @return \Illuminate\View\View
     */
    public function database()
    {
        if ( ! $this->checkDatabaseConnection() ) {
            return redirect()->back()->withErrors([
                'database_connection' => trans('installer_messages.environment.wizard.form.db_connection_failed'),
            ]);
        }

        ini_set('max_execution_time', 600); //600 seconds = 10 minutes

        $response = $this->databaseManager->migrateAndSeed();

        return redirect()->route('Installer.final')->with(['message' => $response]);
    }

    /**
     * Validate database connection with user credentials (Form Wizard).
     *
     * @return boolean
     */
    private function checkDatabaseConnection()
    {
        try {
            DB::connection()->getPdo();
            return true;
        } catch (Exception $e) {
            return false;
        }
    }
}

app/Http/Controllers/Installer/FinalController.php
<?php

namespace App\Http\Controllers\Installer;

use Illuminate\Routing\Controller;
use App\Http\Controllers\Installer\Helpers\DatabaseManager;
use App\Http\Controllers\Installer\Helpers\EnvironmentManager;
use App\Http\Controllers\Installer\Helpers\FinalInstallManager;
use App\Http\Controllers\Installer\Helpers\InstalledFileManager;

class FinalController extends Controller
{
    /**
     * Update installed file and display finished view.
     *
     * @param InstalledFileManager $fileManager
     * @return \Illuminate\View\View
     */
    public function final(FinalInstallManager $finalInstall, EnvironmentManager $environment)
    {
        $finalMessages = $finalInstall->runFinal();
        // $finalStatusMessage = $fileManager->update();
        $finalEnvFile = $environment->getEnvContent();

        return view('installer.finished', compact('finalMessages', 'finalEnvFile'));
    }

    /**
     * Seed the database.
     *
     * @return \Illuminate\View\View
     */
    public function seedDemo(DatabaseManager $databaseManager)
    {
        $response = $databaseManager->seedDemoData();

        return redirect()->route('Installer.finish');
    }

    /**
     * Update installed file and display finished view.
     *
     * @param InstalledFileManager $fileManager
     * @return \Illuminate\View\View
     */
    public function finish(InstalledFileManager $fileManager)
    {
        $finalStatusMessage = $fileManager->update();

        return redirect()->to(config('installer.redirectUrl'))->with('message', $finalStatusMessage);
    }
}

app/Http/Controllers/Installer/Helpers/MigrationsHelper.php
<?php

namespace App\Http\Controllers\Installer\Helpers;
use Illuminate\Support\Facades\DB;

trait MigrationsHelper {

    /**
     * Get the migrations in /database/migrations
     *
     * @return array Array of migrations name, empty if no migrations are existing
     */
    public function getMigrations()
    {
        $migrations = glob(database_path().DIRECTORY_SEPARATOR.'migrations'.DIRECTORY_SEPARATOR.'*.php');
        return str_replace('.php', '', $migrations);
    }

    /**
     * Get the migrations that have already been ran.
     *
     * @return Illuminate\Support\Collection List of migrations
     */
    public function getExecutedMigrations()
    {
        // migrations table should exist, if not, user will receive an error.
        return DB::table('migrations')->get()->pluck('migration');
    }
}

resources/views/installer/activate.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.verify.verify_purchase') }}
@endsection

@section('title')
    <i class="fa fa-code fa-fw" aria-hidden="true"></i> {{ trans('installer_messages.verify.verify_purchase') }}
@endsection

@section('container')

    @if(session()->has('failed'))
        <div class="alert alert-danger">
            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
            {{ session()->get('failed') }}
        </div>
    @endif

    {{-- <div class="alert alert-warning"><i class="fa fa-info-circle"></i> {!! trans('installer_messages.environment.classic.backup') !!}</div> --}}
    <form method="post" action="{{ route('Installer.verify') }}">
        {!! csrf_field() !!}
        <div class="form-group">
            <label for="email_address"> {{ trans('installer_messages.verify.form.email_address_label') }} </label>
            <input type="text" name="email_address" id="email_address" value="{{ old('email_address') }}" placeholder="{{ trans('installer_messages.verify.form.email_address_placeholder') }}" required />
        </div>

        <div class="form-group">
            <label for="purchase_code"> {{ trans('installer_messages.verify.form.purchase_code_label') }} </label>
            <input type="text" name="purchase_code" id="purchase_code" value="{{ old('purchase_code') }}" placeholder="{{ trans('installer_messages.verify.form.purchase_code_placeholder') }}" required />
        </div>

        <div class="form-group">
            <label for="root_url"> {{ trans('installer_messages.verify.form.root_url_label') }} </label>
            <input type="text" name="root_url" id="root_url" value="{{ rtrim(env('APP_URL'), '/') }}" placeholder="{{ trans('installer_messages.verify.form.root_url_placeholder') }}" required />
        </div>

        <div class="buttons">
            <button class="button" type="submit">
                <i class="fa fa-check fa-fw" aria-hidden="true"></i>
                {!! trans('installer_messages.verify.submit') !!}
                <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
            </button>

            {{-- <a class="button" href="{{ route('Installer.database') }}" onclick="changeText()">
                <i class="fa fa-check fa-fw" aria-hidden="true"></i>
                {!! trans('installer_messages.environment.classic.install') !!}
                <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
            </a> --}}
        </div>
    </form>

    @if( isset($environment['errors']))
{{--         <div class="buttons">
            <a class="button" href="{{ route('Installer.database') }}" onclick="changeText()">
                <i class="fa fa-check fa-fw" aria-hidden="true"></i>
                {!! trans('installer_messages.environment.classic.install') !!}
                <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
            </a>
        </div>
    @else --}}
        <div class="alert alert-danger">
            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
            {{ trans('installer_messages.environment.classic.required') }}
        </div>
    @endif

@endsection

resources/views/installer/environment-classic.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.environment.classic.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-code fa-fw" aria-hidden="true"></i> {{ trans('installer_messages.environment.classic.title') }}
@endsection

@section('container')

    <div class="alert alert-warning"><i class="fa fa-info-circle"></i> {!! trans('installer_messages.environment.classic.backup') !!}</div>
    <form method="post" action="{{ route('Installer.environmentSaveClassic') }}">
        {!! csrf_field() !!}

        <textarea class="textarea" name="envConfig" style="background-color: #2b303b; color: #c0c5ce">{{ $envConfig }}</textarea>

        <div class="buttons buttons--right">
            <button class="button button--light" type="submit" onclick="btnBusy(event)">
            	<i class="fa fa-floppy-o fa-fw" aria-hidden="true"></i>
             	{!! trans('installer_messages.environment.classic.save') !!}
            </button>
        </div>
    </form>

    @if( ! isset($environment['errors']))
        <div class="buttons">
            <a class="button" href="{{ route('Installer.activate') }}" onclick="changeText()">
                <i class="fa fa-check fa-fw" aria-hidden="true"></i>
                {!! trans('installer_messages.verify.verify_purchase') !!}
                <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
            </a>
        </div>
    @else
        <div class="alert alert-danger">
            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
            {{ trans('installer_messages.environment.classic.required') }}
        </div>
    @endif

@endsection

resources/views/installer/environment.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.environment.menu.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-cog fa-fw" aria-hidden="true"></i>
    {!! trans('installer_messages.environment.menu.title') !!}
@endsection

@section('container')

    <p class="text-center">
        {!! trans('installer_messages.environment.menu.desc') !!}
    </p>
    <div class="buttons">
        <a href="{{ route('Installer.environmentClassic') }}" class="button button-classic">
            <i class="fa fa-code fa-fw" aria-hidden="true"></i> {{ trans('installer_messages.environment.menu.classic-button') }}
        </a>
    </div>

@endsection

resources/views/installer/finished.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.final.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-flag-checkered fa-fw" aria-hidden="true"></i>
    {{ trans('installer_messages.final.title') }}
@endsection

@section('container')
	{{--
	@if(session('message')['dbOutputLog'])
		<p><strong><small>{{ trans('installer_messages.final.migration') }}</small></strong></p>
		<pre><code>{{ session('message')['dbOutputLog'] }}</code></pre>
	@endif --}}

	{{-- <p><strong><small>{{ trans('installer_messages.final.console') }}</small></strong></p>
	<pre><code>{{ $finalMessages }}</code></pre> --}}

	{{-- <p><strong><small>{{ trans('installer_messages.final.log') }}</small></strong></p> --}}
	{{-- <code>{{ $finalStatusMessage }}</code> --}}

	{{-- <p><strong><small>{{ trans('installer_messages.final.env') }}</small></strong></p> --}}
	{{-- <pre><code>{{ $finalEnvFile }}</code></pre> --}}

	<br/><br/>

    <div class="buttons">
        <a href="{{ route('Installer.seedDemo') }}" class="button" onclick="btnBusy(event)" style="background-color: transparent; color: #1d73a2; border: 1px solid #1d73a2;" >
         	{!! trans('installer_messages.final.import_demo_data') !!}
            <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
        </a>

        <a href="{{ route('Installer.finish') }}" class="button">{{ trans('installer_messages.final.exit') }}</a>
    </div>

@endsection

resources/views/installer/install.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.environment.classic.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-code fa-fw" aria-hidden="true"></i> {{ trans('installer_messages.environment.classic.title') }}
@endsection

@section('container')
    @if($license_notifications_array['notification_case'] == "notification_license_ok")
        <div class="alert alert-warning"><i class="fa fa-info-circle"></i> {{ trans('installer_messages.verified') }}</div>

        <div class="buttons">
            <a class="button" href="{{ route('Installer.database') }}" onclick="changeText()">
                <i class="fa fa-check fa-fw" aria-hidden="true"></i>
                {!! trans('installer_messages.finish') !!}
                <i class="fa fa-angle-double-right fa-fw" aria-hidden="true"></i>
            </a>
        </div>

{{--    @else--}}
{{--        <div class="alert alert-danger">--}}
{{--            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>--}}
{{--            {{ trans('installer_messages.verification_failed') }}--}}
{{--        </div>--}}
    @endif
@endsection

resources/views/installer/permissions.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.permissions.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-key fa-fw" aria-hidden="true"></i>
    {{ trans('installer_messages.permissions.title') }}
@endsection

@section('container')

    <ul class="list">
        @foreach($permissions['permissions'] as $permission)
        <li class="list__item list__item--permissions {{ $permission['isSet'] ? 'success' : 'error' }}">
            {{ $permission['folder'] }}
            <span>
                <i class="fa fa-fw fa-{{ $permission['isSet'] ? 'check-circle-o' : 'exclamation-circle' }}"></i>
                {{ $permission['permission'] }}
            </span>
        </li>
        @endforeach
    </ul>

    @if ( ! isset($permissions['errors']))
        <div class="buttons">
            <a href="{{ route('Installer.environmentClassic') }}" class="button">
                {{ trans('installer_messages.permissions.next') }}
                <i class="fa fa-angle-right fa-fw" aria-hidden="true"></i>
            </a>
        </div>
    @else
        <div class="alert alert-danger">
            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
            {{ trans('installer_messages.permissions.required') }}
        </div>
    @endif

@endsection

resources/views/installer/requirements.blade.php
@extends('installer.layouts.master')

@section('template_title')
    {{ trans('installer_messages.requirements.templateTitle') }}
@endsection

@section('title')
    <i class="fa fa-list-ul fa-fw" aria-hidden="true"></i>
    {{ trans('installer_messages.requirements.title') }}
@endsection

@section('container')

    @foreach($requirements['requirements'] as $type => $requirement)
        <ul class="list">
            <li class="list__item list__title {{ $phpSupportInfo['supported'] ? 'success' : 'error' }}">
                <strong>{{ ucfirst($type) }}</strong>
                @if($type == 'php')
                    <strong>
                        <small>
                            (version {{ $phpSupportInfo['minimum'] }} required)
                        </small>
                    </strong>
                    <span class="float-right">
                        <strong>
                            {{ $phpSupportInfo['current'] }}
                        </strong>
                        <i class="fa fa-fw fa-{{ $phpSupportInfo['supported'] ? 'check-circle-o' : 'exclamation-circle' }} row-icon" aria-hidden="true"></i>
                    </span>
                @endif
            </li>
            @foreach($requirements['requirements'][$type] as $extention => $enabled)
                <li class="list__item {{ $enabled ? 'success' : 'error' }}">
                    {{ $extention }}
                    <i class="fa fa-fw fa-{{ $enabled ? 'check-circle-o' : 'exclamation-circle' }} row-icon" aria-hidden="true"></i>
                </li>
            @endforeach
        </ul>
    @endforeach

    @if ( ! isset($requirements['errors']) && $phpSupportInfo['supported'] )
        <div class="buttons">
            <a class="button" href="{{ route('Installer.permissions') }}">
                {{ trans('installer_messages.requirements.next') }}
                <i class="fa fa-angle-right fa-fw" aria-hidden="true"></i>
            </a>
        </div>
    @else
        <div class="alert alert-danger">
            <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
            {{ trans('installer_messages.requirements.required') }}
        </div>
    @endif

@endsection